image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - deploy

deploy:
  stage: deploy
  script:
  - npm i -g npm-check-updates to update
  - npm audit fix
  - ncu -u
  - npm install --save
  - npm run heroku-postbuild