image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - deploy

deploy:
  stage: deploy
  script:
  - npm install -g npm-check-updates
  - ncu -u
  - npm install --save
  - npm run-script heroku-postbuild